CREATE TABLE "TEST"."EMPLOYEE" 
(	
	"ID" NUMBER(28, 0), 
	"NAME" VARCHAR2(50 CHAR), 
	"SURNAME" VARCHAR2(50 CHAR), 
	"DEPARTMENT" VARCHAR2(50 CHAR), 
	"TMS_INSERT" TIMESTAMP (6)
);

CREATE UNIQUE INDEX "TEST"."EMPLOYEE_KEY" ON "TEST"."EMPLOYEE" ("ID");

ALTER TABLE "TEST"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
USING INDEX "TEST"."EMPLOYEE_KEY" ENABLE;

CREATE SEQUENCE "TEST"."EMPLOYEE_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 74476 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
